apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  namespace: python-on-k8s
  labels:
    run: connectApi
spec:
  containers:
    - name: client
      image: rembli/python-on-k8s
      ports:
        - containerPort: 3000
