apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: python-on-k8s
  labels:
    app: python-api    
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: python-api
